### ISSUE TITLE
Both releases are the same file

### ISSUE THREAD

**Issue by ImmortalZypther** [paradoxally/Apollo-User-Agent-Fix#1]
The rootless version is the same as the rootful version, please upload the rootless version!

**Comment by paradoxally** [comment]
Hello.

Which iOS version and jailbreak did you test them on? 

The rootless `.deb` is the file I ran through Derootifier. The rootful one is the one I compiled directly from source.

**Comment by paradoxally** [comment]
Ok, Derootifier might have not worked properly. You can grab the rootful deb and try running it on your end through Derootifier.

**Comment by paradoxally** [comment]
@ImmortalZypther I compiled a deb with rootless support. Should be good now.
